// SPIN ROOM — catalogue des disques (artistes, albums et prix fictifs)
// Source unique utilisée par l'accueil (index.html) et le catalogue (catalogue.html).
//
// Champs : id (= nom de l'image dans pochettes/), artiste, titre, genre, annee,
// etat ("neuf" ou "occasion"), note (état d'un disque d'occasion : NM, VG+, VG, G+),
// prix (en euros), couleur (facultatif : vinyle coloré), selection (facultatif :
// position dans « La sélection du moment »), ajout (plus grand = arrivé plus récemment),
// description (une phrase pour la fiche produit).
//
// Pour ajouter un disque : une ligne ici + l'image pochettes/<id>.jpg

const DISQUES = [
  {"id": "kid-lazarus-eastside-psalms", "artiste": "Kid Lazarus", "titre": "Eastside Psalms", "genre": "Rap", "annee": 2019, "etat": "neuf", "prix": 27.9, "selection": 3, "ajout": 30, "description": "Un premier album brut, porté par des samples de gospel et des textes sur le quartier qui l'a vu grandir."},
  {"id": "riviera-tapes-coastline-disco", "artiste": "Riviera Tapes", "titre": "Coastline Disco", "genre": "French Touch", "annee": 2021, "etat": "neuf", "prix": 29.9, "couleur": "#f2a2b6", "selection": 2, "ajout": 29, "description": "De la disco filtrée au soleil couchant : basses rondes, guitares funky et voix passées au vocoder."},
  {"id": "kasia-wren-frequencies", "artiste": "Kasia Wren", "titre": "Frequencies", "genre": "Électro", "annee": 2016, "etat": "occasion", "note": "NM", "prix": 22.9, "ajout": 28, "description": "Une électro minimaliste et hypnotique, construite à partir de synthés analogiques et de boucles patientes."},
  {"id": "the-lighthouse-kids-static-weather", "artiste": "The Lighthouse Kids", "titre": "Static Weather", "genre": "Rock", "annee": 2018, "etat": "neuf", "prix": 26.9, "couleur": "#f0d23a", "ajout": 27, "description": "Du rock indé nerveux, entre guitares saturées et refrains qu'on chante dès la deuxième écoute."},
  {"id": "ezra-cole-quintet-blue-hour-sessions", "artiste": "Ezra Cole Quintet", "titre": "Blue Hour Sessions", "genre": "Jazz", "annee": 1961, "etat": "occasion", "note": "VG+", "prix": 32.9, "couleur": "#2c5aa0", "selection": 1, "ajout": 26, "description": "Cinq musiciens, une seule prise par morceau : un jazz modal feutré, enregistré à l'heure bleue."},
  {"id": "grace-holloway-sugar-and-static", "artiste": "Grace Holloway", "titre": "Sugar & Static", "genre": "Soul", "annee": 2023, "etat": "neuf", "prix": 34.9, "couleur": "#e9662b", "selection": 5, "ajout": 25, "description": "Une soul pop sucrée aux arrangements rétro, avec une voix qui crépite comme une vieille radio."},
  {"id": "lion-harbour-salt-water-roots", "artiste": "Lion Harbour", "titre": "Salt Water Roots", "genre": "Reggae", "annee": 1979, "etat": "occasion", "note": "VG", "prix": 18.9, "ajout": 24, "description": "Un reggae roots chaleureux, basse ronde et cuivres, enregistré face à la mer."},
  {"id": "lena-moss-paper-moons", "artiste": "Lena Moss", "titre": "Paper Moons", "genre": "Folk", "annee": 2022, "etat": "neuf", "prix": 24.9, "ajout": 23, "description": "Une folk intime, guitare et voix, pour les soirs calmes et les dimanches matin."},
  {"id": "marlowe-grant-gold-teeth-sunday", "artiste": "Marlowe Grant", "titre": "Gold Teeth Sunday", "genre": "Rap", "annee": 2020, "etat": "neuf", "prix": 31.9, "couleur": "#c9a227", "ajout": 22, "description": "Un rap clinquant et assumé, entre productions dorées et punchlines du dimanche."},
  {"id": "paloma-disco-club-neon-boulevard", "artiste": "Paloma Disco Club", "titre": "Neon Boulevard", "genre": "French Touch", "annee": 2007, "etat": "occasion", "note": "VG+", "prix": 21.9, "ajout": 21, "description": "Une French Touch nocturne qui file sur les boulevards, entre house filtrée et lumières de néon."},
  {"id": "atlas-kid-satellite-love", "artiste": "Atlas Kid", "titre": "Satellite Love", "genre": "Électro", "annee": 2012, "etat": "occasion", "note": "VG", "prix": 19.9, "selection": 6, "ajout": 20, "description": "Une électro rêveuse qui mélange nappes spatiales et rythmiques douces, comme une histoire d'amour en orbite."},
  {"id": "harlow-street-granite-hearts", "artiste": "Harlow Street", "titre": "Granite Hearts", "genre": "Rock", "annee": 2004, "etat": "occasion", "note": "NM", "prix": 24.9, "selection": 4, "ajout": 19, "description": "Un rock solide et mélancolique, porté par une batterie lourde et des guitares en clair-obscur."},
  {"id": "odette-vance-late-tide", "artiste": "Odette Vance", "titre": "Late Tide", "genre": "Jazz", "annee": 1958, "etat": "occasion", "note": "VG+", "prix": 28.9, "ajout": 18, "description": "Une voix grave et des balais sur la caisse claire : un jazz vocal intimiste, enregistré à la marée basse."},
  {"id": "the-sunday-gospel-machine-brighter-days", "artiste": "The Sunday Gospel Machine", "titre": "Brighter Days", "genre": "Soul", "annee": 1974, "etat": "occasion", "note": "VG", "prix": 23.9, "ajout": 17, "description": "Une soul gospel lumineuse, chœurs puissants et orgue Hammond, qui donne envie de se lever."},
  {"id": "velvet-stairwell-concrete-lullabies", "artiste": "Velvet Stairwell", "titre": "Concrete Lullabies", "genre": "Rap", "annee": 2017, "etat": "neuf", "prix": 26.9, "ajout": 16, "description": "Un rap introspectif et lo-fi, comme des berceuses écrites dans une cage d'escalier."},
  {"id": "tomo-arden-synthetic-light", "artiste": "Tomo Arden", "titre": "Synthetic Light", "genre": "Électro", "annee": 2024, "etat": "neuf", "prix": 28.9, "ajout": 95, "description": "Une électro lumineuse et géométrique, faite de synthés brillants et de motifs qui s'emboîtent."},
  {"id": "the-honey-engines-velvet-fuzz", "artiste": "The Honey Engines", "titre": "Velvet Fuzz", "genre": "Rock", "annee": 1998, "etat": "occasion", "note": "G+", "prix": 14.9, "ajout": 14, "description": "Du rock garage poisseux, pédales fuzz à fond et énergie de répétition dans un sous-sol."},
  {"id": "hollis-brandt-trio-smoke-and-brass", "artiste": "Hollis Brandt Trio", "titre": "Smoke & Brass", "genre": "Jazz", "annee": 1963, "etat": "occasion", "note": "NM", "prix": 35.9, "ajout": 13, "description": "Un trio piano, contrebasse et batterie : un jazz enfumé de club, élégant et sans détour."},
  {"id": "billie-hart-last-dance-in-july", "artiste": "Billie Hart", "titre": "Last Dance in July", "genre": "Soul", "annee": 2025, "etat": "neuf", "prix": 33.9, "couleur": "#7a2e5a", "ajout": 97, "description": "Une soul romantique et cinématographique, cordes et voix, pour la dernière danse de l'été."},
  {"id": "duke-morrow-overtime", "artiste": "Duke Morrow", "titre": "Overtime", "genre": "Rap", "annee": 2009, "etat": "occasion", "note": "VG+", "prix": 20.9, "ajout": 11, "description": "Un rap efficace et sans fioritures, écrit entre deux services de nuit."},
  {"id": "silas-grey-monochrome-summer", "artiste": "Silas Grey", "titre": "Monochrome Summer", "genre": "Électro", "annee": 2023, "etat": "neuf", "prix": 27.9, "ajout": 10, "description": "Une électro en noir et blanc, froide en surface mais traversée de mélodies chaudes."},
  {"id": "northern-cassettes-wires-and-weather", "artiste": "Northern Cassettes", "titre": "Wires & Weather", "genre": "Rock", "annee": 2006, "etat": "occasion", "note": "VG", "prix": 17.9, "ajout": 9, "description": "Une pop-rock du nord, guitares claires et mélodies sous un ciel toujours changeant."},
  {"id": "dexter-bloom-quartet-after-hours-club", "artiste": "Dexter Bloom Quartet", "titre": "After Hours Club", "genre": "Jazz", "annee": 2024, "etat": "neuf", "prix": 36.9, "ajout": 96, "description": "Un quartet qui joue quand le club ferme ses portes : swing, cuivres et improvisations tardives."},
  {"id": "ruby-okafor-golden-frequency", "artiste": "Ruby Okafor", "titre": "Golden Frequency", "genre": "Soul", "annee": 2022, "etat": "neuf", "prix": 29.9, "ajout": 7, "description": "Une soul afro chaleureuse, percussions et cuivres, qui brille comme une fréquence dorée."},
  {"id": "moreno-kane-fog-and-concrete", "artiste": "Moreno Kane", "titre": "Fog & Concrete", "genre": "Rap", "annee": 2015, "etat": "occasion", "note": "NM", "prix": 25.9, "ajout": 6, "description": "Un rap sombre et atmosphérique, entre brouillard du matin et béton des grands ensembles."},
  {"id": "koji-amano-tokyo-rain-loops", "artiste": "Koji Amano", "titre": "Tokyo Rain Loops", "genre": "Électro", "annee": 2025, "etat": "neuf", "prix": 24.9, "ajout": 98, "description": "Des boucles lo-fi douces et pluvieuses, idéales pour travailler ou rêver la nuit."},
  {"id": "the-midnight-couriers-long-way-home", "artiste": "The Midnight Couriers", "titre": "Long Way Home", "genre": "Rock", "annee": 2021, "etat": "neuf", "prix": 27.9, "ajout": 4, "description": "Un rock de route, guitares ouvertes et refrains pour les longs trajets de nuit."},
  {"id": "jaylen-oakes-late-checkout", "artiste": "Jaylen Oakes", "titre": "Late Checkout", "genre": "Rap", "annee": 2026, "etat": "neuf", "prix": 28.9, "ajout": 99, "description": "Un rap détendu et soyeux, comme une matinée qui traîne dans une chambre d'hôtel."},
  {"id": "the-wilder-hotel-room-404", "artiste": "The Wilder Hotel", "titre": "Room 404", "genre": "Rock", "annee": 2011, "etat": "occasion", "note": "VG+", "prix": 22.9, "ajout": 2, "description": "Un rock indé un peu étrange, plein de détours, enregistré dans une chambre d'hôtel introuvable."},
  {"id": "cash-monroe-southside-gospel", "artiste": "Cash Monroe", "titre": "Southside Gospel", "genre": "Rap", "annee": 2026, "etat": "neuf", "prix": 30.9, "couleur": "#2f6b4f", "ajout": 100, "description": "Un rap habité qui mêle chœurs gospel, basses lourdes et récits du sud de la ville."}
];

// Petites aides partagées
const prixTexte = p => p.toFixed(2).replace(".", ",") + " €";
const pochette = d => "pochettes/" + d.id + ".jpg";
const fiche = d => "disque.html?id=" + d.id;
const NOTES = { NM: "Quasi neuf", "VG+": "Très bon état", VG: "Bon état", "G+": "État correct" };
